### ISSUE TITLE
咨询电子书架

### ISSUE THREAD

**Issue by Jhonwivk** [xnzone/hugo-theme-bookstack#1]
请问page页怎么显示>开关啊
1    （需要一个>)
  1.1
  1.2

**Comment by xnzone** [comment]
> 请问page页怎么显示>开关啊 1 （需要一个>) 1.1 1.2

![image](https://user-images.githubusercontent.com/60599181/208244480-e22b6012-c2a3-4e9a-9242-ba8f7d8a6bce.png)
具体是指这样的效果吗？如果是这样的效果的话，`bookCollapseSection: true`就可以了，具体可以参考我的 https://github.com/xnzone/bookstack。 效果就是 https://bookstack.xnzone.eu.org/
